### ISSUE TITLE
mysqldump: Got errno 32 on write

### ISSUE THREAD

**Issue by kingzbauer** [siddontang/go-mysql-elasticsearch#167]
```
INFO[0000] create BinlogSyncer with config {1001 mysql 127.0.0.1 3306 root   utf8 false false <nil> false 0 0s 0s} 
INFO[0000] skip master data, get current binlog position (mysql-bin.000003, 107) 
INFO[0000] try dump MySQL and parse                     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049a3c]

goroutine 12 [running]:
sync/atomic.AddUint64(0x18e5a90c, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go/sync2.(*AtomicInt64).Add(0x18e5a90c, 0x1, 0x0, 0x18e72280, 0x13)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go/sync2/atomic.go:52 +0x31
github.com/siddontang/go-mysql-elasticsearch/river.(*River).makeRequest(0x18e4fcc0, 0x18e62230, 0x8311e4d, 0x6, 0x18f32180, 0x1, 0x1, 0x7, 0x82c1c80, 0x0, ...)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/river/sync.go:193 +0x2f1
github.com/siddontang/go-mysql-elasticsearch/river.(*River).makeInsertRequest(0x18e4fcc0, 0x18e62230, 0x18f32180, 0x1, 0x1, 0x1, 0x10, 0x18, 0x18e0f030, 0x18e4dc00)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/river/sync.go:203 +0x53
github.com/siddontang/go-mysql-elasticsearch/river.(*eventHandler).OnRow(0x18e0ef20, 0x18e4dc00, 0x82c1c80, 0x18e0f030)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/river/sync.go:73 +0x2fb
github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/canal.(*dumpParseHandler).Data(0x18e4da80, 0x18e12fd5, 0x7, 0x18f640dd, 0x19, 0x18eee200, 0x13, 0x20, 0x4, 0x835cf80)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/canal/dump.go:67 +0x77d
github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump.Parse(0x847eff0, 0x18e0ef68, 0x84809d0, 0x18e4da80, 0x816f300, 0x1, 0x0)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump/parser.go:81 +0x26f
github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump.(*Dumper).DumpAndParse.func1(0x18e0ef68, 0x84809d0, 0x18e4da80, 0x18e9a900, 0x18f0c1c0)
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump/dump.go:182 +0x4e
created by github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump.(*Dumper).DumpAndParse
	/home/deploy/go/src/github.com/siddontang/go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump/dump.go:181 +0x11a
root@server:/usr/local/es# mysqldump: Got errno 32 on write
```

**Comment by siddontang** [comment]
Is it a 32-bit operating system?

**Comment by kingzbauer** [comment]
Kindly help me understand the error. I don't understand how we end up with a nil pointer, mostly like `r.st` https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/sync.go#L193

**Comment by siddontang** [comment]
@kingzbauer 

Seem that Atomic Int64 is not supported in 32-bit system. 

I suggest using 64-bit operating system.

**Comment by kingzbauer** [comment]
Oh okay, that sucks.
I wrote a simple script to test it out, seems to work fine.
```go
package main

import "sync/atomic"
import "fmt"

func main() {
     var i int64
     i = atomic.AddInt64(&i, 4)
     fmt.Println(i)
}
```

**Comment by siddontang** [comment]
you can use 
```
type C struct {
   a int
   b int64
}

var c C
atomic.AddInt64(&c.b, 1)
```

I remember that the offset of the atomic int64 value in the struct must be 8 bytes alignment

**Comment by kingzbauer** [comment]
Yes, that's it. I've come across these, so probably it's the same issue package main https://github.com/golang/go/issues/6404

**Comment by kingzbauer** [comment]
Thanks for your time @siddontang
