### ISSUE TITLE
mysqldump: Got errno 32 on write

### ISSUE THREAD

**Issue by Faizanq** [siddontang/go-mysql-elasticsearch#285]
mysqldump: Got errno 32 on write
[2018/08/02 14:36:47] [info] main.go:95 context is done with context canceled, closing
[2018/08/02 14:36:47] [info] river.go:313 closing river
[2018/08/02 14:36:47] [info] canal.go:224 closing canal
[2018/08/02 14:36:47] [info] binlogsyncer.go:140 syncer is closing...
[2018/08/02 14:36:47] [info] binlogsyncer.go:155 syncer is closed
[2018/08/02 14:36:47] [info] master.go:54 save position (, 0)

**Comment by siddontang** [comment]
please list full logs above the errno 32.

How do you run the application?

**Comment by Faizanq** [comment]
qureshi@qureshi:~/go_work/src/github.com/siddontang/go-mysql-elasticsearch$ go-mysql-elasticsearch 
[2018/08/02 20:19:26] [info] binlogsyncer.go:111 create BinlogSyncer with config {1001 mysql 127.0.0.1 3306 root   utf8 false false <nil> false false 0 0s 0s 0}
[2018/08/02 20:19:26] [info] dump.go:140 try dump MySQL and parse
[2018/08/02 20:19:26] [info] status.go:53 run status http server 127.0.0.1:12800
[2018/08/02 20:19:26] [info] dump.go:190 exec mysqldump with [--host=127.0.0.1 --port=3306 --user=root --password=123 --master-data --single-transaction --skip-lock-tables --compact --skip-opt --quick --no-create-info --skip-extended-insert --hex-blob --default-character-set=utf8 go_elastic user_master]
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got errno 32 on write
[2018/08/02 20:19:27] [info] main.go:95 context is done with context canceled, closing
[2018/08/02 20:19:27] [info] river.go:313 closing river
[2018/08/02 20:19:27] [info] canal.go:224 closing canal
[2018/08/02 20:19:27] [info] binlogsyncer.go:140 syncer is closing...
[2018/08/02 20:19:27] [info] binlogsyncer.go:155 syncer is closed
[2018/08/02 20:19:27] [info] master.go:54 save position (, 0)
[2018/08/02 20:19:27] [error] canal.go:210 canal dump mysql err: make insert ES request err table go_elastic.user_master has no column name tag, close sync
[2018/08/02 20:19:27] [error] river.go:299 start canal err make insert ES request err table go_elastic.user_master has no column name tag, close sync
qureshi@qureshi:~/go_work/src/github.com/siddontang/go-mysql-elasticsearch$

**Comment by siddontang** [comment]
you can google `mysqldump: Got errno 32 on write`

**Comment by Faizanq** [comment]
I tried all solution but didn't work, If I found I will post here for others.

**Comment by siddontang** [comment]
seem you can disable `mysqldump` and see whether this is the problem for the `mysqldump` or others.

**Comment by vovolie** [comment]
Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events.
panic: interface conversion: interface {} is nil, not string

goroutine 26 [running]:

go-mysql-elasticsearch/vendor/github.com/siddontang/go-mysql/dump/dump.go:204 +0x1a9
mysqldump: Got errno 32 on write
