### ISSUE TITLE
http: invalid pattern 这是什么错误

### ISSUE THREAD

**Issue by fang1344** [siddontang/go-mysql-elasticsearch#359]
[root@iZj6cgsi8ovf1m7mty7zw0Z go-mysql-elasticsearch]# bin/go-mysql-elasticsearch -config=river.toml
[2019/12/20 13:37:19] [info] binlogsyncer.go:141 create BinlogSyncer with config {1001 mysql 127.0.0.1 3306 root    false false <nil> false UTC false 0 0s 0s 0 false 0}
[2019/12/20 13:37:19] [info] dump.go:185 skip dump, no mysqldump
panic: http: invalid pattern

goroutine 13 [running]:
net/http.(*ServeMux).Handle(0x12c6300, 0x0, 0x0, 0xbc3aa0, 0xc0000a1bc0)
	/usr/lib/golang/src/net/http/server.go:2397 +0x33a
net/http.Handle(...)
	/usr/lib/golang/src/net/http/server.go:2446
github.com/siddontang/go-mysql-elasticsearch/river.InitStatus(0xc000034740, 0xf, 0x0, 0x0)
	/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/metrics.go:52 +0x5d
created by github.com/siddontang/go-mysql-elasticsearch/river.NewRiver
	/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:79 +0x3d9

**Comment by tskynn** [comment]
你解决了吗？是否可以告诉一下解决方案呢？

**Comment by syscall0x80** [comment]
这个pr https://github.com/siddontang/go-mysql-elasticsearch/pull/340 增加了新的配置， 如果是旧的配置文件升级新的代码， 没有加这行配置就会有这个报错
![image](https://user-images.githubusercontent.com/5652393/75051506-f8c54a80-5508-11ea-9ffa-0e4946c8dd1b.png)

**Comment by anyanfei** [comment]
要不是因为楼上说了解决办法，我真是脑壳都要抠破了~感谢感谢
